# Remarkable document: dummy
# Generated by PDF Extract Tool

puts "size 1404 1872"  # Standard Remarkable size (portrait)

puts "pen black"
puts "line_width 1"

# Title
puts "set_font Roman 24"
puts "text 50 50 \"dummy\""

# Heading level 2
puts "set_font Roman 20"
puts "text 50 145.0 \"Dumm y PDF file\""